--
-- PostgreSQL database cluster dump
--

-- Started on 2025-04-02 15:27:20

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-02 15:27:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-04-02 15:27:21

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-02 15:27:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16386)
-- Name: pgagent; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA pgagent;


ALTER SCHEMA pgagent OWNER TO postgres;

--
-- TOC entry 5002 (class 0 OID 0)
-- Dependencies: 7
-- Name: SCHEMA pgagent; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA pgagent IS 'pgAgent system tables';


--
-- TOC entry 2 (class 3079 OID 16387)
-- Name: pgagent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgagent WITH SCHEMA pgagent;


--
-- TOC entry 5003 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION pgagent; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgagent IS 'A PostgreSQL job scheduler';


--
-- TOC entry 253 (class 1255 OID 16633)
-- Name: registrar_log(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.registrar_log() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO log (operacao, detalhes) 
    VALUES (TG_OP, row_to_json(NEW)::text);
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.registrar_log() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 244 (class 1259 OID 16717)
-- Name: Cadastros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cadastros" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Numero" integer NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL
);


ALTER TABLE public."Cadastros" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16716)
-- Name: Cadastros_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cadastros" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cadastros_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16725)
-- Name: LogOperacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LogOperacoes" (
    "Id" integer NOT NULL,
    "Operacao" text NOT NULL,
    "DataOperacao" timestamp with time zone NOT NULL,
    "CadastroId" integer NOT NULL
);


ALTER TABLE public."LogOperacoes" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16724)
-- Name: LogOperacoes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LogOperacoes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LogOperacoes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16648)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16594)
-- Name: cadastro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cadastro (
    id integer NOT NULL,
    descricao text NOT NULL,
    valor numeric NOT NULL,
    CONSTRAINT cadastro_valor_check CHECK ((valor > (0)::numeric))
);


ALTER TABLE public.cadastro OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16593)
-- Name: cadastro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cadastro_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cadastro_id_seq OWNER TO postgres;

--
-- TOC entry 5004 (class 0 OID 0)
-- Dependencies: 240
-- Name: cadastro_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cadastro_id_seq OWNED BY public.cadastro.id;


--
-- TOC entry 4793 (class 2604 OID 16597)
-- Name: cadastro id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cadastro ALTER COLUMN id SET DEFAULT nextval('public.cadastro_id_seq'::regclass);


--
-- TOC entry 4755 (class 0 OID 16388)
-- Dependencies: 225
-- Data for Name: pga_jobagent; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobagent (jagpid, jaglogintime, jagstation) FROM stdin;
8328	2025-03-25 23:20:16.655379-03	Jaqcpacheco
9688	2025-03-31 11:11:24.392854-03	Jaqcpacheco
\.


--
-- TOC entry 4756 (class 0 OID 16397)
-- Dependencies: 227
-- Data for Name: pga_jobclass; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobclass (jclid, jclname) FROM stdin;
\.


--
-- TOC entry 4757 (class 0 OID 16407)
-- Dependencies: 229
-- Data for Name: pga_job; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_job (jobid, jobjclid, jobname, jobdesc, jobhostagent, jobenabled, jobcreated, jobchanged, jobagentid, jobnextrun, joblastrun) FROM stdin;
\.


--
-- TOC entry 4759 (class 0 OID 16455)
-- Dependencies: 233
-- Data for Name: pga_schedule; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_schedule (jscid, jscjobid, jscname, jscdesc, jscenabled, jscstart, jscend, jscminutes, jschours, jscweekdays, jscmonthdays, jscmonths) FROM stdin;
\.


--
-- TOC entry 4760 (class 0 OID 16483)
-- Dependencies: 235
-- Data for Name: pga_exception; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_exception (jexid, jexscid, jexdate, jextime) FROM stdin;
\.


--
-- TOC entry 4761 (class 0 OID 16497)
-- Dependencies: 237
-- Data for Name: pga_joblog; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_joblog (jlgid, jlgjobid, jlgstatus, jlgstart, jlgduration) FROM stdin;
\.


--
-- TOC entry 4758 (class 0 OID 16431)
-- Dependencies: 231
-- Data for Name: pga_jobstep; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobstep (jstid, jstjobid, jstname, jstdesc, jstenabled, jstkind, jstcode, jstconnstr, jstdbname, jstonerror, jscnextrun) FROM stdin;
\.


--
-- TOC entry 4762 (class 0 OID 16513)
-- Dependencies: 239
-- Data for Name: pga_jobsteplog; Type: TABLE DATA; Schema: pgagent; Owner: postgres
--

COPY pgagent.pga_jobsteplog (jslid, jsljlgid, jsljstid, jslstatus, jslresult, jslstart, jslduration, jsloutput) FROM stdin;
\.


--
-- TOC entry 4994 (class 0 OID 16717)
-- Dependencies: 244
-- Data for Name: Cadastros; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cadastros" ("Id", "Nome", "Numero", "DataCriacao") FROM stdin;
1	Stefanie 	141414	2025-04-02 15:07:36.007079-03
2	jaqueline	848	2025-04-02 15:07:55.400443-03
3	Jaquelineeeeee	15848	2025-04-02 15:12:20.914986-03
4	Jaqueline	25147	2025-04-02 15:14:57.468473-03
\.


--
-- TOC entry 4996 (class 0 OID 16725)
-- Dependencies: 246
-- Data for Name: LogOperacoes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LogOperacoes" ("Id", "Operacao", "DataOperacao", "CadastroId") FROM stdin;
3	Novo cadastro	2025-04-02 15:12:21.832226-03	3
4	Novo cadastro	2025-04-02 15:14:58.229063-03	4
\.


--
-- TOC entry 4992 (class 0 OID 16648)
-- Dependencies: 242
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250324224921_CriarTabelaCadastro	9.0.3
20250402171413_AdicionarDataCadastro	9.0.3
20250402175036_AdicionarDataCriacao	9.0.3
20250402180515_CriarBanco	9.0.3
\.


--
-- TOC entry 4991 (class 0 OID 16594)
-- Dependencies: 241
-- Data for Name: cadastro; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cadastro (id, descricao, valor) FROM stdin;
\.


--
-- TOC entry 5005 (class 0 OID 0)
-- Dependencies: 243
-- Name: Cadastros_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cadastros_Id_seq"', 4, true);


--
-- TOC entry 5006 (class 0 OID 0)
-- Dependencies: 245
-- Name: LogOperacoes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LogOperacoes_Id_seq"', 4, true);


--
-- TOC entry 5007 (class 0 OID 0)
-- Dependencies: 240
-- Name: cadastro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cadastro_id_seq', 1, false);


--
-- TOC entry 4836 (class 2606 OID 16723)
-- Name: Cadastros PK_Cadastros; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cadastros"
    ADD CONSTRAINT "PK_Cadastros" PRIMARY KEY ("Id");


--
-- TOC entry 4839 (class 2606 OID 16731)
-- Name: LogOperacoes PK_LogOperacoes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogOperacoes"
    ADD CONSTRAINT "PK_LogOperacoes" PRIMARY KEY ("Id");


--
-- TOC entry 4834 (class 2606 OID 16652)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4830 (class 2606 OID 16602)
-- Name: cadastro cadastro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cadastro
    ADD CONSTRAINT cadastro_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 16604)
-- Name: cadastro valor_unico; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cadastro
    ADD CONSTRAINT valor_unico UNIQUE (valor);


--
-- TOC entry 4837 (class 1259 OID 16737)
-- Name: IX_LogOperacoes_CadastroId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LogOperacoes_CadastroId" ON public."LogOperacoes" USING btree ("CadastroId");


--
-- TOC entry 4841 (class 2620 OID 16645)
-- Name: cadastro trg_log_delete; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_log_delete AFTER DELETE ON public.cadastro FOR EACH ROW EXECUTE FUNCTION public.registrar_log();


--
-- TOC entry 4842 (class 2620 OID 16636)
-- Name: cadastro trigger_delete; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_delete AFTER DELETE ON public.cadastro FOR EACH ROW EXECUTE FUNCTION public.registrar_log();


--
-- TOC entry 4843 (class 2620 OID 16634)
-- Name: cadastro trigger_insert; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_insert AFTER INSERT ON public.cadastro FOR EACH ROW EXECUTE FUNCTION public.registrar_log();


--
-- TOC entry 4844 (class 2620 OID 16635)
-- Name: cadastro trigger_update; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_update AFTER UPDATE ON public.cadastro FOR EACH ROW EXECUTE FUNCTION public.registrar_log();


--
-- TOC entry 4840 (class 2606 OID 16732)
-- Name: LogOperacoes FK_LogOperacoes_Cadastros_CadastroId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LogOperacoes"
    ADD CONSTRAINT "FK_LogOperacoes_Cadastros_CadastroId" FOREIGN KEY ("CadastroId") REFERENCES public."Cadastros"("Id") ON DELETE CASCADE;


-- Completed on 2025-04-02 15:27:21

--
-- PostgreSQL database dump complete
--

-- Completed on 2025-04-02 15:27:21

--
-- PostgreSQL database cluster dump complete
--

